// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB29nIBeak1dZ7o6hLj9cQqJnD2F1e7L28',
    appId: '1:375554088193:android:acf943320fd69992a78f00',
    messagingSenderId: '375554088193',
    projectId: 'moodapp-f2f2f',
    storageBucket: 'moodapp-f2f2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDphYDDGnik0p-EW-xfJh_I3lFy9J1SVeU',
    appId: '1:375554088193:ios:6d7042bd29f34f8da78f00',
    messagingSenderId: '375554088193',
    projectId: 'moodapp-f2f2f',
    storageBucket: 'moodapp-f2f2f.appspot.com',
    iosClientId: '375554088193-967rgaoohu7ohndsuf73cseneonjg801.apps.googleusercontent.com',
    iosBundleId: 'com.example.trial0201',
  );
}
